#pragma once

enum MGS2WeaponIndex : uint8_t
{
    MGS2_WEAPON_INDEX_NONE = 0x0,
    MGS2_WEAPON_INDEX_M9 = 0x1,
    MGS2_WEAPON_INDEX_USP = 0x2,
    MGS2_WEAPON_INDEX_SOCOM = 0x3,
    MGS2_WEAPON_INDEX_PSG1 = 0x4,
    MGS2_WEAPON_INDEX_RGB6 = 0x5,
    MGS2_WEAPON_INDEX_NIKITA = 0x6,
    MGS2_WEAPON_INDEX_STINGER = 0x7,
    MGS2_WEAPON_INDEX_CLAYMORE = 0x8,
    MGS2_WEAPON_INDEX_C4 = 0x9,
    MGS2_WEAPON_INDEX_CHAFF_GRENADE = 0xA,
    MGS2_WEAPON_INDEX_STUN_GRENADE = 0xB,
    MGS2_WEAPON_INDEX_D_MIC = 0xC,
    MGS2_WEAPON_INDEX_HIGH_FREQUENCY_BLADE = 0xD,
    MGS2_WEAPON_INDEX_COOLANT = 0xE,
    MGS2_WEAPON_INDEX_AKS74U = 0xF,
    MGS2_WEAPON_INDEX_MAGAZINE = 0x10,
    MGS2_WEAPON_INDEX_GRENADE = 0x11,
    MGS2_WEAPON_INDEX_M4 = 0x12,
    MGS2_WEAPON_INDEX_PSG1T = 0x13,
    MGS2_WEAPON_INDEX_D_MIC_ZOOMED = 0x14,
    MGS2_WEAPON_INDEX_BOOK = 0x15,

    MGS2_WEAPON_INDEX_MAX_WEAPONS = 0x16,

    MGS2_WEAPON_INDEX_PLAYER_ATTACK = 0x17,
    MGS2_WEAPON_INDEX_BLADE_FAINT = 0x18,
    MGS2_WEAPON_INDEX_BLADE_STAB = 0x19,
    MGS2_WEAPON_INDEX_BLADE_GUARD = 0x1A,
    MGS2_WEAPON_INDEX_BOX_REMOVE = 0x1B,
    MGS2_WEAPON_INDEX_KICK1 = 0x1C,
};


enum MGS2ItemIndex : uint8_t
{
    MGS2_ITEM_INDEX_NONE = 0x0,  /// Unarmed / no item
    MGS2_ITEM_INDEX_RATION = 0x1,
    MGS2_ITEM_INDEX_DUMMY_SCOPE = 0x2,  /// Dummy binoculars
    MGS2_ITEM_INDEX_MEDICINE = 0x3,
    MGS2_ITEM_INDEX_STYPTIC = 0x4,  ///bandage
    MGS2_ITEM_INDEX_DIAZEPAM = 0x5,  /// pentazemin
    MGS2_ITEM_INDEX_UNIFORM = 0x6,  /// BDU
    MGS2_ITEM_INDEX_BODY_ARMOR = 0x7,
    MGS2_ITEM_INDEX_STEALTH = 0x8,
    MGS2_ITEM_INDEX_MINE_DETECTOR = 0x9,

    MGS2_ITEM_INDEX_BOMB_SENSOR_A = 0xA,
    MGS2_ITEM_INDEX_BOMB_SENSOR_B = 0xB,
    MGS2_ITEM_INDEX_NIGHT_VISION_GOGGLES = 0xC,
    MGS2_ITEM_INDEX_THERMAL_GOGGLES = 0xD,
    MGS2_ITEM_INDEX_SCOPE = 0xE,
    MGS2_ITEM_INDEX_CAMERA = 0xF,
    MGS2_ITEM_INDEX_CARDBOARD_BOX_A = 0x10,
    MGS2_ITEM_INDEX_CIGARETTES = 0x11,
    MGS2_ITEM_INDEX_ID_CARD = 0x12,
    MGS2_ITEM_INDEX_SHAVER = 0x13,

    MGS2_ITEM_INDEX_PHS = 0x14, /// Cell phone
    MGS2_ITEM_INDEX_TANKER_CAMERA = 0x15,
    MGS2_ITEM_INDEX_CARDBOARD_BOX_B = 0x16,
    MGS2_ITEM_INDEX_CARDBOARD_BOX_C = 0x17,
    MGS2_ITEM_INDEX_WET_CARDBOARD_BOX = 0x18,
    MGS2_ITEM_INDEX_VIBRATION_SENSOR = 0x19,
    MGS2_ITEM_INDEX_CARDBOARD_BOX_D = 0x1A,
    MGS2_ITEM_INDEX_CARDBOARD_BOX_E = 0x1B,
    MGS2_ITEM_INDEX_RAZOR = 0x1C, //cut body razor?
    MGS2_ITEM_INDEX_SOCOM_SUPPRESSOR = 0x1D,

    MGS2_ITEM_INDEX_AKS74U_SUPPRESSOR = 0x1E,
    MGS2_ITEM_INDEX_DUMMY_TANKER_CAMERA = 0x1F,
    MGS2_ITEM_INDEX_INFINITY_BANDANA = 0x20,
    MGS2_ITEM_INDEX_DOG_TAG = 0x21,
    MGS2_ITEM_INDEX_MO_DISC = 0x22,
    MGS2_ITEM_INDEX_USP_SUPPRESSOR = 0x23,
    MGS2_ITEM_INDEX_INFINITY_WIG = 0x24,
    MGS2_ITEM_INDEX_WIG_A = 0x25, /// Wig A (infinite O2)
    MGS2_ITEM_INDEX_WIG_B = 0x26, /// Wig B (infinite grip)
    MGS2_ITEM_INDEX_WIG_C = 0x27, //?

    MGS2_ITEM_INDEX_WIG_D = 0x28, //?

    MGS2_ITEM_INDEX_MAX_ITEMS = 0x29,
};
