						;;;;;;;;;; Visual Settings ;;;;;;;;;;

[Output Resolution]
; Enter your chosen output resolution.
; You can leave these at 0 if you want your desktop resolution used instead.
Enabled = true
Width = 0
Height = 0
Windowed = false
Borderless = true

[Internal Resolution]
; Set internal rendering resolution.
; You can leave these at 0 if you want the resolution to be same as your output resolution.
Width = 0
Height = 0

[Anisotropic Filtering]
; Anisotropic Filtering: valid values are 0 - 16
; Experimental, may take effect on more textures than it should
Samples = 16

[Disable Texture Filtering]
; Disables all texture filtering, making the game look like minecraft with blocky textures.
DisableTextureFiltering = false

[Vector Line Fix]
; Fixes scaling for vector/line based effects in 2 & 3, such as rain, lasers, bullet trails, ect
; which weren't properly scaled up from their PS2 resolutions.
; Generally want to keep this to false. 
Enabled = true
; Scaling Size: Lower numbers increase the width of vector/line effects. You can calculate the scale as Screen Height / Desired Pixel Width,
; ie (1080 Resolution / 4 Pixel Width = 270 Scale). The number will be automatically adjusted to the nearest whole pixel, don't worry about decimals.
; 360 scale is pixel-accurate to PCSX2's corrected line widths across all resolutions - 1 pixel @ 448/OG PS2 Res, 2 @ 720p, 3 @ 1080p, 4 @ 1440, 6 @ 2160.
Line Scale = 360

[Effect Speed Fixes]
; Fixes various effects throughout MGS2 & MGS3 which originally had their durations tuned for the PS2's FPS slowdowns during intense cutscenes
; Resulting in them running at double (or higher) their intended speed & ending early on modern / more powerful hardware.
Enabled = true

						;;;;;; Ultrawide/Narrower Fixes ;;;;;;

[Fix Aspect Ratio]
; Fixes aspect ratio and removes pillarboxing in MGS2/MGS3.
Enabled = true

[Fix HUD]
; Experimental. Will break some effects.
; Scales HUD/movies to 16:9.
Enabled = false

[Fix FOV]
; Converts FOV to vert- and matches 16:9 horizontal FOV.
; Only applies at <16:9. Will be disabled if aspect ratio is >1.778~.
Enabled = true

[Framebuffer Fix]
; Forces the framebuffer size to be the same as the custom resolution.
; Disable this if you want pillarboxing/letterboxing with your custom resolution.
Enabled = true

						;;;;;;;;;; Tweaks & Fixes ;;;;;;;;;;

[Launcher Config]
; If enabled will skip the launcher app and run the game directly
; (options like game language & button style will need to be configured below)
SkipLauncher = false
; If enabled, the launcher will skip all splashscreens and jump straight to the launch game screen.
LauncherJumpStart = false

; Which in-game controller icons to display: PS5, PS4, XBOX, NX, STMD, KBD
CtrlType = KBD
; Language (may depend on Region setting): EN, JP, FR, GR, IT, PR, SP, DU, RU
Language = EN
; Region (MGS3 only): US, JP, EU
Region = US

; MSXGame (MG1/MG2 only): which MSX game to launch, MG1 or MG2
MSXGame = MG1
; MSXWallType (MG1/MG2 only): which wallpaper style to use (0 to 6)
MSXWallType = 0
; MSXWallAlign (MG1/MG2 only): orientation of game screen (L, R, or C for center)
MSXWallAlign = C
						
[Force Stereo Audio]
; If your Windows audio output device is INCORRECTLY set to output 5.1 audio, the game will output sounds to audio channels that do not exist. 
; For example, codec/radio conversations will be FAR QUIETER than other sound effects (such as rain), or outright missing throughout the game.
; Razer Synapse's THX Virtualization and SteelSeries Sonar's ChatMix features are known to cause this. 
; THIS IS A SYMPTOM OF A HARDWARE CONFIGURATION ISSUE. THIS OVERRIDE IS ONLY HERE FOR IF YOU'RE TOO LAZY TO FIX IT PROPERLY.
; Other games -will- still have this issue, so it's best to fix the actual problem.
; If enabled, the game is forced to output stereo audio.
Enabled = false

[Skip Intro Logos]
; Skips the unskippable KONAMI etc logo images on startup, skippable intro videos will still be played
; Skipping logos for MG1 / MG2 (the MSX games) not currently supported.
Enabled = true

[Disable Mouse Cursor]
; Stops the mouse cursor from showing in the launcher and game.
Enabled = true

[Mouse Sensitivity]
; Multiplies X/Y position of reported cursor position to increase sensitivity.
; Higher multipliers produce more sensitivity.
Enabled = false
X Multiplier = 1
Y Multiplier = 1

[Texture Buffer]
; MG1/2 | MGS3: Extends the maximum VRAM allocation size /PER TEXTURE/, allowing textures larger than 128MB to be loaded
; Setting to the game default of 128 or lower will disable extending
SizeMB = 128

[Pause on Focus Loss]
; If the game should pause when alt-tabbed.
; Default / vanilla behavior is true.
PauseOnFocusLoss = true
; Fixes assets not loading properly when alt-tabbed during level transitions & cutscenes.
; Speedrunners utilize the vanilla/bugged behavior where assets don't load properly to skip forced codec calls, 
; though it can also result in doors not loading properly - softlocking the game.
; Generally want this set to true.
CutsceneLoadingFix = true

[MG1 Custom Loading Screens]
; Adds support for 1080p/1440p/4k loading screens to MG1/MG2 while using a custom Output Resolution.
; Place custom loading screens in "MG and MG2\Misc\loading\_win" 
; load_fh.ctxr, load_wq.ctxr, load_4k.ctxr, load_fh_jp.ctxr, load_wq_jp.ctxr, load_4k_jp.ctxr
Enabled = false


						;;;;;;;;;; MGSHDFix / Internal Settings ;;;;;;;;;;

[Verbose Logging]
; Outputs additional information to the MGSHDFix.log file to assist in debugging.
Enabled = false

[Config Version]
;Keep this at the bottom
Version = 2
