name: Create Release

env:
  CI: true

on:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Extract version from version.h
      id: extract_version
      shell: bash
      run: |
        VERSION_FILE="src/resources/version.h"
        echo "Reading version from $VERSION_FILE"

        VERSION_MAJOR=$(grep '#define VERSION_MAJOR' "$VERSION_FILE" | awk '{print $3}')
        VERSION_MINOR=$(grep '#define VERSION_MINOR' "$VERSION_FILE" | awk '{print $3}')
        VERSION_PATCH=$(grep '#define VERSION_PATCH' "$VERSION_FILE" | awk '{print $3}')

        version="${VERSION_MAJOR}.${VERSION_MINOR}.${VERSION_PATCH}"
        echo "Parsed version: $version"

        echo "version=$version" >> $GITHUB_OUTPUT

    - name: Verify release does not already exist
      shell: pwsh
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        $version = "${{ steps.extract_version.outputs.version }}"

        Write-Host "Checking whether release/tag already exists for version $version..."

        $releaseExists = gh release view $version --repo "${{ github.repository }}" 2>$null

        if ($LASTEXITCODE -eq 0) {
          Write-Error "Release posting already exists for version $version. Bump version.h before creating a new release."
          exit 1
        }

        $tagExists = git ls-remote --tags origin "refs/tags/$version"

        if ($tagExists) {
          Write-Error "Git tag already exists for version $version. Bump version.h before creating a new release."
          exit 1
        }

        Write-Host "No existing release or tag found for version $version."

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    # wxWidgets cache setup
    - name: Get wxWidgets submodule hash
      id: wxhash
      run: |
        cd external/wxWidgets
        $hash = git rev-parse HEAD
        "hash=$hash" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Cache wxWidgets
      uses: actions/cache@v4
      with:
        path: external/wxWidgets/lib/vc_x64_lib
        key: wxwidgets-${{ runner.os }}-${{ steps.wxhash.outputs.hash }}

    # SDL3 cache setup
    - name: Get SDL3 submodule hash
      id: sdlhash
      run: |
        cd external/SDL
        $hash = git rev-parse HEAD
        "hash=$hash" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Cache SDL3
      uses: actions/cache@v4
      with:
        path: external/SDL/build/msvc-x64-static
        key: sdl3-${{ runner.os }}-vs2022-v143-x64-static-v3-${{ steps.sdlhash.outputs.hash }}

    # Zydis cache setup
    - name: Get Zydis submodule hash
      id: zydishash
      run: |
        cd external/zydis
        $hash = git rev-parse HEAD
        "hash=$hash" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Cache Zydis
      uses: actions/cache@v4
      with:
        path: |
          external/zydis/msvc/bin/ReleaseX64
          external/zydis/msvc/bin/ReleaseX86
        key: zydis-${{ runner.os }}-${{ steps.zydishash.outputs.hash }}

    # -------------------------
    # Prepare output structure
    # -------------------------
    - run: mkdir dist
    - run: mkdir dist/plugins
    - run: mkdir dist/logs


    # Download Ultimate ASI Loader
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        latest: true
        fileName: "Ultimate-ASI-Loader_x64.zip"

    - name: Extract Loader
      run: Expand-Archive Ultimate-ASI-Loader_x64.zip -DestinationPath dist

    - name: Add Loader License
      run: Invoke-WebRequest https://raw.githubusercontent.com/ThirteenAG/Ultimate-ASI-Loader/master/license -OutFile dist/UltimateASILoader_LICENSE.md

    - name: Stage Loader DLLs
      run: |
        Copy-Item dist/dinput8.dll dist/wininet.dll
        Move-Item dist/dinput8.dll dist/winhttp.dll

    # -------------------------
    # Build
    # -------------------------
    - name: Build
      run: msbuild "${{ github.event.repository.name }}.sln" /m -t:rebuild -verbosity:minimal -property:Configuration=Release -property:Platform=x64 -property:PlatformToolset=v143

    # Copy built binaries directly into plugins\
    - run: Copy-Item "x64\Release\${{ github.event.repository.name }}.asi" "dist/plugins/${{ github.event.repository.name }}.asi"
    - run: Copy-Item "x64\Release\${{ github.event.repository.name }} Config Tool.exe" "dist/plugins/${{ github.event.repository.name }} Config Tool.exe"

    # Logs & metadata
    - run: Copy-Item README.md "dist/logs/${{ github.event.repository.name }}_Game.log"
    - run: Copy-Item README.md "dist/logs/${{ github.event.repository.name }}_Launcher.log"
    - run: Copy-Item README.md "dist/plugins/${{ github.event.repository.name }}_README.md"
    - run: Copy-Item LICENSE.md "dist/plugins/${{ github.event.repository.name }}_LICENSE.md"

    - run: Copy-Item "external\SMAA\LICENSE.txt" "dist/plugins/SMAA_LICENSE.md"
    - run: Copy-Item "external\SMAA\SMAA.hlsl" "dist/plugins/SMAA.hlsl"

    # Package release zips
    - name: Create MGS2 Nexus / Base Github Release zip
      working-directory: dist
      run: 7z a -tzip "../${{ github.event.repository.name }}_${{ steps.extract_version.outputs.version }}.zip" *

    - name: Create MG1 + MG2 Nexus zip
      run: |
        Copy-Item dist dist_variant1 -Recurse

        Add-Content "dist_variant1/logs/${{ github.event.repository.name }}_Game.log" "1"

        cd dist_variant1
        7z a -tzip "../${{ github.event.repository.name }}_${{ steps.extract_version.outputs.version }}_MG1.zip" *
        cd ..
        Remove-Item dist_variant1 -Recurse -Force

    - name: Create MGS3 Nexus zip
      run: |
        Copy-Item dist dist_variant3 -Recurse

        Add-Content "dist_variant3/logs/${{ github.event.repository.name }}_Game.log" "3"

        cd dist_variant3
        7z a -tzip "../${{ github.event.repository.name }}_${{ steps.extract_version.outputs.version }}_MGS3.zip" *
        cd ..
        Remove-Item dist_variant3 -Recurse -Force

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ github.event.repository.name }}_${{ steps.extract_version.outputs.version }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.extract_version.outputs.version }}
        name: "${{ steps.extract_version.outputs.version }}"
        draft: true
        generateReleaseNotes: true
        artifactErrorsFailBuild: true

    - name: Upload to NexusMods - MG1 + MG2
      uses: Nexus-Mods/upload-action@v1.0.0-beta.9
      with:
        api_key: ${{ secrets.NEXUSMODS_API_KEY }}
        file_id: 107230
        display_name: "MGSHDFix"
        filename: ${{ github.event.repository.name }}_${{ steps.extract_version.outputs.version }}_MG1.zip
        version: "${{ steps.extract_version.outputs.version }}"
        category: main
        archive_existing_version: true
        primary_mod_manager_download: true
        description: Set both Internal Resolution & Internal Upscaling to Default / Original in the game's launcher. (Resolution is entirely handled by MGSHDFix.)
            
    - name: Upload to NexusMods - MGS2
      uses: Nexus-Mods/upload-action@v1.0.0-beta.9
      with:
        api_key: ${{ secrets.NEXUSMODS_API_KEY }}
        file_id: 462574
        display_name: "MGSHDFix"
        filename: ${{ github.event.repository.name }}_${{ steps.extract_version.outputs.version }}.zip
        version: "${{ steps.extract_version.outputs.version }}"
        category: main
        archive_existing_version: true
        primary_mod_manager_download: true
        description: |
            Set both Internal Resolution & Internal Upscaling to Default / Original in the game's launcher. (Resolution is entirely handled by MGSHDFix.)

            Texture / Movie resolution is not affected / can be set however desired.


    - name: Upload to NexusMods - Upload to NexusMods - MGS3
      uses: Nexus-Mods/upload-action@v1.0.0-beta.9
      with:
        api_key: ${{ secrets.NEXUSMODS_API_KEY }}
        file_id: 541612
        display_name: "MGSHDFix"
        filename: ${{ github.event.repository.name }}_${{ steps.extract_version.outputs.version }}_MGS3.zip
        version: "${{ steps.extract_version.outputs.version }}"
        category: main
        archive_existing_version: true
        primary_mod_manager_download: true
        update_mod_version: true
        description: |
            Set both Internal Resolution & Internal Upscaling to Default / Original in the game's launcher. (Resolution is entirely handled by MGSHDFix.)

            Texture / Movie resolution is not affected / can be set however desired.
