name: MGSHDFix CI Builds

env:
  CI: true

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Get wxWidgets submodule hash
      id: wxhash
      run: |
        cd external/wxWidgets
        $hash = git rev-parse HEAD
        "hash=$hash" | Out-File -FilePath $env:GITHUB_OUTPUT -Append -Encoding utf8

    - name: Cache wxWidgets
      uses: actions/cache@v4
      with:
        path: external/wxWidgets/lib/vc_x64_lib
        key: wxwidgets-${{ runner.os }}-${{ steps.wxhash.outputs.hash }}

    - name: Build
      run: msbuild "${{ github.event.repository.name }}.sln" /m -t:rebuild -verbosity:minimal -property:Configuration=Release -property:Platform=x64

    # Prepare output structure
    - run: mkdir dist
    - run: mkdir dist/plugins
    - run: mkdir dist/logs

    # Copy built binaries directly into plugins/
    - run: Copy-Item "x64\Release\${{ github.event.repository.name }}.asi" "dist/plugins/${{ github.event.repository.name }}.asi"
    - run: Copy-Item "x64\Release\${{ github.event.repository.name }} Config Tool.exe" "dist/plugins/${{ github.event.repository.name }} Config Tool.exe"

    # Download Ultimate ASI Loader
    - uses: robinraju/release-downloader@v1.8
      with:
        repository: "ThirteenAG/Ultimate-ASI-Loader"
        latest: true
        fileName: "Ultimate-ASI-Loader_x64.zip"

    - name: Extract Loader
      run: Expand-Archive Ultimate-ASI-Loader_x64.zip -DestinationPath dist

    - name: Add Loader License
      run: Invoke-WebRequest https://raw.githubusercontent.com/ThirteenAG/Ultimate-ASI-Loader/master/license -OutFile dist/UltimateASILoader_LICENSE.md

    - name: Stage Loader DLLs
      run: |
        Copy-Item dist/dinput8.dll dist/wininet.dll
        Move-Item dist/dinput8.dll dist/winhttp.dll

    # Logs & metadata
    - run: Copy-Item README.md "dist/logs/${{ github.event.repository.name }}_Game.log"
    - run: Copy-Item README.md "dist/logs/${{ github.event.repository.name }}_Launcher.log"
    - run: Copy-Item README.md "dist/plugins/${{ github.event.repository.name }}_README.md"
    - run: Copy-Item LICENSE.md "dist/plugins/${{ github.event.repository.name }}_LICENSE.md"

    # Package everything
    - name: Create release zip
      run: 7z a -tzip "${{ github.event.repository.name }}-run-${{ github.run_number }}.zip" dist\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}-run-${{ github.run_number }}
        path: dist/
